import { IMG } from '@/lib/images'

export const EVENTS = [
  {
    slug: 'downtown-town-hall',
    date: 'Jun 10',
    fullDate: 'Wednesday, June 10, 2026',
    time: '6:30 PM',
    endTime: '8:30 PM',
    title: 'Downtown Town Hall',
    place: 'Beaverton Civic Center',
    address: '12725 SW Millikan Way, Beaverton, OR 97005',
    city: 'Beaverton, OR',
    tag: 'Town Hall',
    img: IMG.eventBeaverton,
    description:
      'An open-format town hall focused on housing, transit, and small business. Bring your questions — every attendee will have a chance to ask one.',
    schedule: [
      { t: '6:30 PM', h: 'Doors open · Light refreshments' },
      { t: '7:00 PM', h: 'Opening remarks' },
      { t: '7:15 PM', h: 'Open floor: housing, transit, and small business' },
      { t: '8:15 PM', h: 'Closing remarks and individual conversations' },
    ],
    capacity: 320,
    rsvped: 187,
  },
  {
    slug: 'columbia-county-meet-and-greet',
    date: 'Jun 12',
    fullDate: 'Friday, June 12, 2026',
    time: '7:00 PM',
    endTime: '9:00 PM',
    title: 'Columbia County Meet & Greet',
    place: 'Riverfront Hall',
    address: '265 Strand St, St. Helens, OR 97051',
    city: 'St. Helens, OR',
    tag: 'Meet & Greet',
    img: IMG.eventStHelens,
    description:
      'Coffee, dessert, and an unhurried evening of conversation. AngelLust will be there for the entire night — no scripted remarks.',
    schedule: [
      { t: '7:00 PM', h: 'Coffee and dessert served' },
      { t: '7:30 PM', h: 'Informal conversations begin' },
      { t: '8:30 PM', h: 'Group Q&A (optional)' },
    ],
    capacity: 180,
    rsvped: 96,
  },
  {
    slug: 'washco-250-celebration',
    date: 'Jun 13',
    fullDate: 'Saturday, June 13, 2026',
    time: '11:00 AM',
    endTime: '3:00 PM',
    title: 'WashCo 250th Year Celebration',
    place: 'Forest Grove Commons',
    address: '1815 Main St, Forest Grove, OR 97116',
    city: 'Forest Grove, OR',
    tag: 'Community',
    img: IMG.eventForestGrove,
    description:
      "A community-led celebration of Washington County's 250th year. The campaign will host a booth and join the afternoon panel.",
    schedule: [
      { t: '11:00 AM', h: 'Family events and exhibits open' },
      { t: '1:00 PM', h: 'Panel discussion: the next 25 years' },
      { t: '2:30 PM', h: 'Booth conversations and signing' },
    ],
    capacity: 600,
    rsvped: 412,
  },
  {
    slug: 'coast-listening-session',
    date: 'Jun 21',
    fullDate: 'Sunday, June 21, 2026',
    time: '4:00 PM',
    endTime: '6:00 PM',
    title: 'Coast Listening Session',
    place: 'Pacific Bay Pier',
    address: 'Pier 14, Tillamook, OR 97141',
    city: 'Tillamook, OR',
    tag: 'Listening Session',
    img: IMG.eventTillamook,
    description:
      'A small-format listening session for the maritime and coastal economy. Limited capacity — RSVP required.',
    schedule: [
      { t: '4:00 PM', h: 'Check-in at the pier' },
      { t: '4:15 PM', h: 'Open conversation: maritime and coastal economy' },
      { t: '5:30 PM', h: 'Informal one-on-ones' },
    ],
    capacity: 80,
    rsvped: 71,
  },
  {
    slug: 'rural-cafe-stops-tour',
    date: 'Jun 27',
    fullDate: 'Saturday, June 27, 2026',
    time: '8:00 AM',
    endTime: '5:00 PM',
    title: 'Rural Café Stops Tour',
    place: 'Five towns · Highway 101',
    address: 'Multi-stop route — see route card',
    city: 'Coastal Route',
    tag: 'Tour',
    img: IMG.eventTillamook,
    description:
      'A back-to-back day of café conversations along the coast. Pop in for any leg — coffee is on the campaign.',
    schedule: [
      { t: '8:00 AM', h: 'Cannon Beach · The Wayfarer' },
      { t: '10:30 AM', h: "Manzanita · Wanda's Café" },
      { t: '12:30 PM', h: 'Tillamook · Pelican Brewing' },
      { t: '2:30 PM', h: 'Pacific City · Stimulus Café' },
      { t: '4:30 PM', h: "Lincoln City · Café C'est La Vie" },
    ],
    capacity: 400,
    rsvped: 188,
  },
]

export const QUOTES = [
  {
    id: 'alvarez',
    quote:
      "AngelLust listens before they speak — and acts before they're asked. That's the kind of representation this district has been missing.",
    full: "We've had our small-business chamber turn over three campaign liaisons in the last cycle. AngelLust is the first person who actually returned the call — and then showed up to a 7 AM meeting in the rain. That's the difference. We have a representative who treats showing up as the baseline, not a press opportunity.",
    name: 'Maria Alvarez',
    role: 'Small-Business Owner',
    org: 'Coastal Chamber of Commerce',
    img: IMG.endorseAlvarez,
  },
  {
    id: 'hollis',
    quote:
      "I've watched a lot of campaigns come through here. This is the first one that actually understood our maritime corridor.",
    full: "I've been on these docks for thirty-two years. Most candidates ask for a photo by the cranes and leave. AngelLust spent three days riding along — at the terminals, on the tugs, in the dispatch booths. The platform reflects what they learned, not a talking point cooked up in a hotel ballroom.",
    name: 'Captain Russell Hollis',
    role: 'Port Operations · 32 years',
    org: 'Maritime Trades Council',
    img: IMG.endorseHollis,
  },
  {
    id: 'nakamura',
    quote: 'Practical, principled, and present. AngelLust shows up to the meetings nobody films.',
    full: "We're a small-town volunteer station. We don't have lobbyists. We have a roster, a budget that never quite covers gear, and a community that depends on us. AngelLust met with us twice before the cameras, and once after. That order matters.",
    name: 'Kai Nakamura',
    role: 'Volunteer Firefighter',
    org: 'District 1 Volunteer Coalition',
    img: IMG.endorseNakamura,
  },
  {
    id: 'river',
    quote: "Finally — a campaign that talks about land management without pretending it's simple.",
    full: "Forest health is complex. Fire policy is complex. Watershed rights are complex. AngelLust doesn't reach for the slogan. They sit at the table with the people who do the work and write policy from there.",
    name: 'Dana Riverstone',
    role: 'Forestry Director',
    org: 'Pacific Land Stewards',
    img: IMG.endorseRiver,
  },
  {
    id: 'sinclair',
    quote:
      'A serious candidate, with a serious plan, who treats this district like the home it is.',
    full: "I taught civics for thirty-one years. I've seen every kind of candidate. AngelLust is the rarest kind: the one who keeps studying after they've already announced. We need more of that, and fewer slogans.",
    name: 'Eleanor Sinclair',
    role: 'Educator · 31 years',
    org: 'Educators United',
    img: IMG.endorseSinclair,
  },
]

export const ORGS = [
  'Coastal Chamber',
  'Maritime Trades Council',
  'Pacific Land Stewards',
  'Veterans for District 1',
  'Small Towns First',
  'Educators United',
  'Public Safety Alliance',
  'Farm + Forest Coalition',
]
